msgid ""
msgstr ""
"Project-Id-Version: Backup Suite\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-07-22 19:19+0200\n"
"PO-Revision-Date: \n"
"Last-Translator: \n"
"Language-Team: Persian Professionals <persianpros@yahoo.com>\n"
"Language: fa_IR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Poedit-SourceCharset: UTF-8\n"
"X-Generator: Poedit 2.1.1\n"
"Plural-Forms: nplurals=2; plural=(n==0 || n==1);\n"

#: ../plugin.py:441
msgid ""
"\n"
"The found files:"
msgstr ""

#: ../plugin.py:358
msgid ""
"\n"
"You are using dual multiboot!"
msgstr ""

#: ../plugin.py:447
#, python-format
msgid "  %s (maybe error)"
msgstr ""

#: ../plugin.py:444
#, python-format
msgid "  %s (maybe ok)"
msgstr ""

#: ../message.py:180
msgid " MB available space"
msgstr ""

#: ../message.py:185
msgid " MB needed space"
msgstr ""

#: ../plugin.py:450
msgid " nothing!"
msgstr ""

#: ../message.py:45
msgid " size to be backed up: "
msgstr ""

#: ../message.py:175
msgid " to make a back-up!"
msgstr ""

#: ../message.py:169
msgid "* * * WARNING * * *"
msgstr ""

#: ../plugin.py:480
msgid "A recording is currently running. Please stop the recording before trying to start a flashing."
msgstr ""

#: ../message.py:70
msgid "Additional backup -> "
msgstr ""

#: ../message.py:35
msgid "BACK-UP TOOL, FOR MAKING A COMPLETE BACK-UP"
msgstr ""

#: ../plugin.py:132
msgid "Backup > HDD"
msgstr ""

#: ../plugin.py:130
msgid "Backup > MMC"
msgstr ""

#: ../plugin.py:133
msgid "Backup > USB"
msgstr ""

#: ../plugin.py:584 ../plugin.py:591
msgid "Backup and restore your image"
msgstr ""

#: ../message.py:149
msgid "Backup done with: "
msgstr ""

#: ../message.py:106
msgid "Backup finished and copied to your USB-flashdrive."
msgstr ""

#: ../plugin.py:338 ../plugin.py:541
msgid "Backup info"
msgstr ""

#: ../plugin.py:583 ../plugin.py:590
msgid "BackupSuite"
msgstr ""

#: ../plugin.py:131 ../plugin.py:233 ../plugin.py:262
msgid "Close"
msgstr ""

#: ../message.py:65
msgid "Create: kerneldump"
msgstr ""

#: ../message.py:60
msgid "Create: root.ubifs"
msgstr ""

#: ../plugin.py:339 ../plugin.py:570
msgid "Delete"
msgstr ""

#: ../plugin.py:567
msgid "Delete backup"
msgstr ""

#: ../plugin.py:540
#, python-format
msgid "Do you really want to unpack %s ?"
msgstr ""

#: ../plugin.py:153
msgid ""
"Do you want to make a back-up on USB?\n"
"\n"
"This only takes a few minutes depending on the used filesystem and is fully automatic.\n"
"\n"
"Make sure you first insert an USB flash drive before you select Yes."
msgstr ""

#: ../plugin.py:150
msgid ""
"Do you want to make an USB-back-up image on HDD? \n"
"\n"
"This only takes a few minutes and is fully automatic.\n"
msgstr ""

#: ../plugin.py:156
msgid ""
"Do you want to make an USB-back-up image on MMC? \n"
"\n"
"This only takes a few minutes and is fully automatic.\n"
msgstr ""

#: ../plugin.py:470
msgid "Exit"
msgstr ""

#: ../plugin.py:484
msgid "Flashing: "
msgstr ""

#: ../plugin.py:369
msgid "For flashing your receiver files are needed:\n"
msgstr ""

#: ../message.py:129
msgid "Full back-up direct to USB"
msgstr ""

#: ../plugin.py:194
msgid "Full back-up on HDD"
msgstr "پشتیبان کامل روی هارد"

#: ../plugin.py:208
msgid "Full back-up on MMC"
msgstr "پشتیبان کامل روی MMC"

#: ../plugin.py:201
msgid "Full back-up to USB"
msgstr "پشتیبان کامل روی USB"

#: ../message.py:235
msgid "Full back-up to the MultiMediaCard"
msgstr ""

#: ../message.py:111
msgid "Full back-up to the harddisk"
msgstr ""

#: ../message.py:123
msgid "If you place an USB-stick containing this file then the back-up will be automatically made onto the USB-stick and can be used to restore the current image if necessary."
msgstr ""

#: ../message.py:90
msgid "Image creation FAILED!"
msgstr ""

#: ../message.py:225
msgid "Installed packages contained in this backup:"
msgstr ""

#: ../message.py:154
msgid "KB per second"
msgstr ""

#: ../plugin.py:127
msgid "Make a backup or restore a backup"
msgstr ""

#: ../message.py:159
msgid "Most likely this back-up can't be restored because of it's size, it's simply too big to restore. This is a limitation of the bootloader not of the back-up or the BackupSuite."
msgstr ""

#: ../plugin.py:45
msgid "NAS"
msgstr ""

#: ../message.py:230
msgid "NFI Image created in: "
msgstr ""

#: ../plugin.py:516
msgid "NOT found files for flashing!\n"
msgstr ""

#: ../message.py:220
msgid "No additional USB-stick found to copy an extra backup"
msgstr ""

#: ../plugin.py:173 ../message.py:30
msgid "No supported receiver found!"
msgstr ""

#: ../message.py:170
msgid "Not enough free space on "
msgstr ""

#: ../plugin.py:458 ../plugin.py:499
msgid "Only kernel"
msgstr ""

#: ../plugin.py:457 ../plugin.py:496
msgid "Only root"
msgstr ""

#: ../message.py:118
msgid "PLEASE READ THIS:"
msgstr ""

#: ../message.py:40
msgid "Please be patient, a backup will now be made, this will take about: "
msgstr ""

#: ../message.py:85
msgid "Please check the manual of the receiver on how to restore the image."
msgstr ""

#: ../plugin.py:234
msgid "Please wait"
msgstr ""

#: ../plugin.py:528
msgid "Please: DO NOT reboot your STB and turn off the power.\n"
msgstr ""

#: ../message.py:215
msgid "Probably you are trying to make the back-up in flash memory"
msgstr ""

#: ../plugin.py:134
msgid "Restore backup"
msgstr ""

#: ../plugin.py:336 ../plugin.py:353 ../plugin.py:362
msgid "Run flash"
msgstr ""

#: ../plugin.py:464 ../plugin.py:511
msgid "Second partition (only kernel)"
msgstr ""

#: ../plugin.py:463 ../plugin.py:508
msgid "Second partition (only root)"
msgstr ""

#: ../plugin.py:462 ../plugin.py:505
msgid "Second partition (root and kernel)"
msgstr ""

#: ../plugin.py:368
msgid "Select parameter for start flash!\n"
msgstr ""

#: ../plugin.py:261
msgid "Select the folder with backup"
msgstr ""

#: ../plugin.py:521
msgid "Show only found image and mtd partitions.\n"
msgstr ""

#: ../plugin.py:455 ../plugin.py:487
msgid "Simulate (no write)"
msgstr ""

#: ../plugin.py:461 ../plugin.py:502
msgid "Simulate second partition (no write)"
msgstr ""

#: ../message.py:55
msgid "Some information about the task"
msgstr ""

#: ../plugin.py:456 ../plugin.py:490
msgid "Standard (root and kernel)"
msgstr ""

#: ../message.py:134
msgid "The content of the folder is:"
msgstr ""

#: ../plugin.py:529
msgid "The image or kernel will be flashing and auto booted in few minutes.\n"
msgstr ""

#: ../message.py:190
msgid "The program will abort, please try another medium with more free space to create your back-up."
msgstr ""

#: ../message.py:124
msgid "The program will exit now."
msgstr ""

#: ../message.py:164
msgid "There COULD be a problem with restoring this back-up because the size of the back-up comes close to the maximum size. This is a limitation of the bootloader not of the back-up or the BackupSuite."
msgstr ""

#: ../message.py:116
msgid "There is NO valid USB-stick found, so I've got nothing to do."
msgstr ""

#: ../message.py:100
msgid "There is a valid USB-flashdrive detected in one of the USB-ports, therefore an extra copy of the back-up image will now be copied to that USB-flashdrive."
msgstr ""

#: ../message.py:101
msgid "This only takes about 20 seconds....."
msgstr ""

#: ../message.py:139
msgid "Time required for this process: "
msgstr ""

#: ../message.py:119
msgid "To back-up directly to the USB-stick, the USB-stick MUST contain a file with the name:"
msgstr ""

#: ../message.py:75
msgid "USB Image created in: "
msgstr ""

#: ../plugin.py:334 ../plugin.py:537
msgid "Unzip"
msgstr ""

#: ../message.py:200
msgid "Using your own custom lookuptable.txt from the folder /etc"
msgstr ""

#: ../message.py:205
msgid "Version unknown, probably not installed the right way."
msgstr ""

#: ../plugin.py:359
msgid ""
"Warning!\n"
"Use at your own risk! Make always a backup before use!\n"
"Don't use it if you use multiple ubi volumes in ubi layer!"
msgstr ""

#: ../plugin.py:232
msgid "What is new since the last release?"
msgstr ""

#: ../plugin.py:571
#, python-format
msgid ""
"You are about to delete this backup:\n"
"\n"
"%s\n"
"Continue?"
msgstr ""

#: ../plugin.py:527
msgid "Your STB will freeze during the flashing process.\n"
msgstr ""

#: ../message.py:80
msgid "and there is made an extra copy in: "
msgstr ""

#: ../message.py:95
msgid "available "
msgstr ""

#: ../message.py:120
msgid "backupstick or"
msgstr ""

#: ../message.py:121
msgid "backupstick.txt"
msgstr ""

#: ../plugin.py:266 ../plugin.py:328
#, python-format
msgid "current:  %s"
msgstr ""

#: ../message.py:195
msgid "is not executable..."
msgstr ""

#: ../message.py:144
msgid "minutes"
msgstr ""

#: ../message.py:50
msgid "not found, the backup process will be aborted!"
msgstr ""

#: ../message.py:210
msgid "not installed yet, now installing"
msgstr ""

#: ../plugin.py:526
msgid "ofgwrite will stop enigma2 now to run the flash.\n"
msgstr ""
